import * as api from './codegen/buildkite-api/api';
import {GraphQLClient} from 'graphql-request';
import * as aws from 'aws-sdk';

export async function getAuthenticatedClient(apiToken: string): Promise<api.Sdk> {
  // Initialise authenticated GraphQL client
  const client = new GraphQLClient('https://graphql.buildkite.com/v1', {
    headers: {
      Authorization: `Bearer ${apiToken}`,
    },
  });

  // Get an instance of the autogenerated sdk
  return api.getSdk(client);
}

export async function getSecretsManagerSecret(
  secretArn: string,
  version?: string
): Promise<aws.SecretsManager.GetSecretValueResponse> {
  const sm = new aws.SecretsManager();
  return sm
    .getSecretValue({
      SecretId: secretArn,
      VersionId: version,
    })
    .promise();
}

export function getSecretsManagerSecretValue(r: aws.SecretsManager.GetSecretValueResponse): string {
  if (r.SecretString) {
    return r.SecretString;
  } else {
    throw new Error('unable to extract secret value from response');
  }
}
